import { WorkExperienceEntry } from "../types";

export const EXPERIENCES: WorkExperienceEntry[] = [
  {
    company: "BairesDev",
    client: "Spring Health",
    clientLink: "https://www.springhealth.com",
    companyLink: "https://www.bairesdev.com",
    modality: "Remote",
    position: "Senior Software Engineer",
    startDate: "Jan 2026",
    endDate: "Present",
    responsibilities: [
      "Unlocked an estimated $460K in projected five-year incremental variable revenue by shipping Spring Health's Medication Management quick view—eligibility-driven client surfacing, one-click referral, and persistent completion state—directly into the care-coordination platform.",
      "Resolved the top-cited Q4 provider NPS/CSAT pain point by architecting HIPAA-compliant file attachments across web and mobile: extended an AWS S3 presigned-URL and virus-scan pipeline via GraphQL on the backend, React Query on web, and Flutter on mobile, with per-role visibility controls enforcing RBAC.",
      "Accelerated provider triage workflows by engineering a React/TypeScript redesign of the clinician portal client panel—clinical quick-filter views, row-level action menus, and role-gated admin and mobile experiences—gated behind LaunchDarkly to enable zero-downtime, percentage-based rollouts.",
      "Cut feature cycle time by integrating AI-assisted engineering workflows (Claude Code, Cursor AI, OpenAI Codex) into day-to-day development—accelerating scaffolding, test coverage, and code review turnaround while maintaining HIPAA-grade code quality standards.",
    ],
    technologies: [
      "React.js",
      "TypeScript",
      "Flutter",
      "Dart",
      "GraphQL",
      "Node.js",
      "Express.js",
      "Redux.js",
      "LaunchDarkly",
      "Jest",
      "Datadog",
      "Mixpanel",
      "Storybook",
      "Claude Code",
      "Cursor AI",
      "OpenAI Codex",
    ],
  },
  {
    company: "EPAM Systems",
    client: "Dow Jones",
    clientLink: "https://www.dowjones.com",
    companyLink: "https://www.epam.com",
    modality: "Remote",
    position: "Senior Software Engineer",
    startDate: "May 2022",
    endDate: "Dec 2025",
    responsibilities: [
      "Accelerated ad-configuration deployment velocity by 45% and auto-detected 85% of anomalies before production by building a dynamic configuration management engine—Next.js/React admin UI, Node.js backend, MongoDB persistence, Redis caching—with template inheritance, versioned audit history, and one-click rollback, achieving 100% change traceability.",
      "Reduced 95th-percentile GraphQL API latency from 350 ms to 120 ms (66%) by profiling slow resolvers with Apollo Engine, optimizing hot paths, and establishing performance budgets in collaboration with AdOps and RevOps stakeholders.",
      "Achieved 99.8% data-mapping accuracy between legacy CMS metadata and Google Ad Manager ad-unit hierarchies by architecting a modular, API-first integration layer using Node.js, Express, and GraphQL.",
      "Adopted GitHub Copilot across the front-end and API teams, pairing AI-assisted code generation with peer review to speed up boilerplate, test scaffolding, and documentation without compromising review rigor.",
    ],
    technologies: [
      "JavaScript",
      "HTML",
      "CSS",
      "TypeScript",
      "React",
      "Styled Components",
      "Next.js",
      "Node.js",
      "Express.js",
      "GraphQL",
      "MongoDB",
      "Redis",
      "AWS",
      "Jenkins",
      "Jest",
      "React Testing Library",
      "NPM",
      "Yarn",
      "NVM",
      "Postman",
      "Jira",
      "Confluence",
      "Google Ads",
      "GitHub Copilot",
    ],
  },
  {
    company: "Newtech S.R.L.",
    client: "Verizon",
    companyLink: "https://www.newtechsa.com/es/inicio",
    clientLink: "https://www.verizon.com",
    modality: "Remote",
    position: "Software Developer",
    startDate: "Aug 2021",
    endDate: "May 2022",
    responsibilities: [
      "Improved end-to-end load times by 18% and shrank the initial bundle by 25% by revamping Verizon's fault-reporting SPA with Angular 11+—enabling AOT compilation, OnPush change detection, and lazy-loaded feature modules.",
      "Reduced regression defects by 30% and eliminated 2,000+ redundant TypeScript lines by enforcing the DRY principle across shared services, cutting technical debt and narrowing the test surface.",
      "Achieved 85% code coverage on critical user flows by building a full test suite with Jasmine, Karma, and Protractor—using HttpTestingController to mock backend responses and validate flows without live services.",
    ],
    technologies: [
      "JavaScript",
      "HTML",
      "CSS",
      "TypeScript",
      "Angular",
      "Angular CLI",
      "RxJS",
      "Node.js",
      "Jasmine",
      "Karma",
      "Postman",
      "GitLab",
      "Jenkins",
      "Jira",
      "Confluence",
    ],
  },
  {
    company: "IntelliSys D. Corp.",
    client: "Escuela Nacional de la Judicatura",
    companyLink: "https://intellisysdcorp.com/",
    clientLink: "https://juriteca.edu.do/base/domenj",
    modality: "On Site",
    position: "Software Engineer",
    startDate: "Nov 2020",
    endDate: "Aug 2021",
    responsibilities: [
      "Mentored & upskilled four junior front-end engineers, conducting weekly one-on-one coaching sessions, pair-programming workshops and structured code reviews. Introduced best practices in JavaScript (ES6+), React, Git and unit testing (Jest, React Testing Library), boosting the team's average story-completion rate by 25%.",
      "Architected and delivered a virtual library of Dominican jurisprudence for academic and legal professionals, collaborating with subject-matter experts to model case metadata and hierarchy. Built a React/Next.js front-end with full-text search and faceted filters, backed by a Node.js/Express API and PostgreSQL datastore. Optimized indexing and query performance—reducing search latency by 40%—and enhanced the legal consultation experience by 13%, as measured in user-satisfaction surveys.",
      "Collaborated cross-functionally with UX designers, legal researchers and QA analysts—gathering requirements, refining user stories in Jira, and authoring technical and user documentation in Confluence to streamline onboarding and maintenance.",
    ],
    technologies: [
      "JavaScript",
      "HTML",
      "CSS",
      "Sass",
      "React",
      "Bootstrap",
      "Node.js",
      "Express.js",
      "PostgreSQL",
      "NPM",
      "Jira",
    ],
  },
  {
    company: "IntelliSys D. Corp.",
    companyLink: "https://intellisysdcorp.com/",
    client: "Consejo Nacional de Competitividad (CNC)",
    clientLink: "https://cnc.gob.do",
    modality: "On Site",
    position: "Software Developer",
    startDate: "Jun 2020",
    endDate: "Nov 2020",
    responsibilities: [
      "Designed and implemented interactive dashboards with D3.js, creating line charts, bar charts, and map graphs that let users explore historical trends, apply category filters, and hover for exact values.",
      "Built a fully responsive UI with HTML5 and CSS3 (Flexbox, Media Queries), ensuring cross-browser compatibility and seamless layouts on desktop, tablet, and mobile. Established a modular design system for reusable chart components and info panels.",
      "Collaborated closely with storytellers and UX designers, running A/B tests and iterating on prototypes based on in-app feedback and usage metrics—resulting in a 31% lift in user satisfaction as measured by post-interact surveys.",
    ],
    technologies: ["JavaScript", "D3.js", "jQuery", "HTML", "CSS", "Jira"],
  },
  {
    company: "IntelliSys D. Corp.",
    client: "IntelliSys D. Corp.",
    companyLink: "https://intellisysdcorp.com/",
    clientLink: "https://intellisysdcorp.com/",
    modality: "On Site",
    position: "Software Engineer",
    startDate: "Apr 2019",
    endDate: "Jun 2020",
    responsibilities: [
      "Streamlined internal data collection pipeline by architecting and deploying Node.js microservices on Google Cloud Platform (Cloud Functions, and Cloud SQL). Each service ingested, validated and normalized employee and project metrics from multiple sources (CSV uploads, Google Spreadsheets, APIs), then wrote consolidated records into PostgreSQL for analytics.",
      "Built an administrative web application using React, Redux, Node.js/Express, HTML5 and Material UI, and Axios for REST API integration. Designed dynamic data grids, search/filter controls and editable forms for employee records, incorporating client-side validation and optimistic UI updates.",
    ],
    technologies: [
      "JavaScript",
      "HTML",
      "CSS",
      "React",
      "Material-UI",
      "Python",
      "Node.js",
      "Express.js",
      "Flask",
      "PostgreSQL",
      "GCP",
      "Jest",
      "NPM",
      "Looker",
      "Google Spreadsheets",
      "Jira",
      "Zoho",
    ],
  },
];
