import { BsFileEarmarkSpreadsheet } from "react-icons/bs";
import { DiMsqlServer } from "react-icons/di";
import {
  FaReact,
  FaNodeJs,
  FaHtml5,
  FaAws,
  FaCss3,
  FaSass,
  FaPython,
} from "react-icons/fa";
import { GiBearFace } from "react-icons/gi";
import {
  SiReact,
  SiExpress,
  SiGraphql,
  SiAmazonwebservices,
  SiMongodb,
  SiRedis,
  SiJest,
  SiJira,
  SiGoogleads,
  SiTypescript,
  SiJavascript,
  SiAngular,
  SiReactivex,
  SiGitlab,
  SiJenkins,
  SiPostgresql,
  SiD3Dotjs,
  SiJquery,
  SiFlask,
  SiGooglecloud,
  SiLooker,
  SiMui,
  SiJasmine,
  SiPostman,
  SiBootstrap,
  SiZoho,
  SiNpm,
  SiConfluence,
  SiNodedotjs,
  SiYarn,
  SiTestinglibrary,
  SiStyledcomponents,
  SiMysql,
  SiDocker,
  SiStripe,
  SiFirebase,
  SiFigma,
  SiTelegram,
  SiPandas,
  SiScikitlearn,
  SiUnity,
  SiExpo,
  SiGoogle,
  SiFlutter,
  SiDart,
  SiDatadog,
  SiMixpanel,
  SiStorybook,
  SiRedux,
  SiClaude,
  SiAnthropic,
  SiOpenai,
} from "react-icons/si";
import { TbBrandCSharp } from "react-icons/tb";

export const TECH_ICONS: Record<
  string,
  { icon: React.ComponentType<{ className?: string }>; color: string }
> = {
  React: { icon: FaReact, color: "#61DAFB" },
  "React.js": { icon: SiReact, color: "#61DAFB" }, // Variación agregada
  "Next.js": { icon: FaReact, color: "#000000" },
  "Node.js": { icon: FaNodeJs, color: "#339933" },
  "Express.js": { icon: SiExpress, color: "#000000" },
  HTML: { icon: FaHtml5, color: "#E34F26" },
  GraphQL: { icon: SiGraphql, color: "#E10098" },
  AWS: { icon: FaAws, color: "#FF9900" },
  "AWS S3": { icon: SiAmazonwebservices, color: "#FF9900" },
  MongoDB: { icon: SiMongodb, color: "#47A248" },
  Redis: { icon: SiRedis, color: "#DC382D" },
  Jest: { icon: SiJest, color: "#C21325" },
  Jira: { icon: SiJira, color: "#0052CC" },
  "Google Ads": { icon: SiGoogleads, color: "#4285F4" },
  "Google Ad Manager": { icon: SiGoogleads, color: "#4285F4" },
  TypeScript: { icon: SiTypescript, color: "#3178C6" },
  JavaScript: { icon: SiJavascript, color: "#F7DF1E" },
  Angular: { icon: SiAngular, color: "#DD0031" },
  "Angular 11+": { icon: SiAngular, color: "#DD0031" },
  "Angular CLI": { icon: SiAngular, color: "#DD0031" },
  RxJS: { icon: SiReactivex, color: "#B7178C" },
  CSS: { icon: FaCss3, color: "#1572B6" },
  GitLab: { icon: SiGitlab, color: "#FC6D26" },
  Jenkins: { icon: SiJenkins, color: "#D33833" },
  Sass: { icon: FaSass, color: "#CC6699" },
  SQL: { icon: SiPostgresql, color: "#336791" },
  "D3.js": { icon: SiD3Dotjs, color: "#F9A03C" },
  jQuery: { icon: SiJquery, color: "#0769AD" },
  Python: { icon: FaPython, color: "#3776AB" },
  Flask: { icon: SiFlask, color: "#000000" },
  GCP: { icon: SiGooglecloud, color: "#4285F4" },
  PostgreSQL: { icon: SiPostgresql, color: "#336791" },
  Looker: { icon: SiLooker, color: "#4285F4" },
  "Material-UI": { icon: SiMui, color: "#007FFF" },
  Jasmine: { icon: SiJasmine, color: "#8A4182" },
  Postman: { icon: SiPostman, color: "#FF6C37" },
  Bootstrap: { icon: SiBootstrap, color: "#7952B3" },
  Zoho: { icon: SiZoho, color: "#0072c6" },
  "Google Spreadsheets": { icon: BsFileEarmarkSpreadsheet, color: "#34a853" },
  NPM: { icon: SiNpm, color: "#cb3837" },
  Karma: { icon: SiJasmine, color: "#8a4182" },
  Protractor: { icon: SiJasmine, color: "#8a4182" },
  Confluence: { icon: SiConfluence, color: "#0052cc" },
  NVM: { icon: SiNodedotjs, color: "#339933" },
  Yarn: { icon: SiYarn, color: "#2c8ebb" },
  "React Testing Library": { icon: SiTestinglibrary, color: "#e33332" },
  "Styled Components": { icon: SiStyledcomponents, color: "#D26AC2" },
  MySQL: { icon: SiMysql, color: "#4479A1" },
  Docker: { icon: SiDocker, color: "#2496ED" },
  "Material UI": { icon: SiMui, color: "#007FFF" },
  Zustand: { icon: GiBearFace, color: "#3E383E" },
  Stripe: { icon: SiStripe, color: "#6772E5" },
  Firebase: { icon: SiFirebase, color: "#FFCA28" },
  Figma: { icon: SiFigma, color: "#F24E1E" },
  "SQL Server": { icon: DiMsqlServer, color: "#CC2927" },
  "Telegram API": { icon: SiTelegram, color: "#0088cc" },
  Pandas: { icon: SiPandas, color: "#150458" },
  Sklearn: { icon: SiScikitlearn, color: "#F7931E" },
  Emotion: { icon: SiStyledcomponents, color: "#DB7093" },
  "Testing Library": { icon: SiTestinglibrary, color: "#E33332" },
  Express: { icon: SiExpress, color: "#000000" },
  Unity: { icon: SiUnity, color: "#000000" },
  "C#": { icon: TbBrandCSharp, color: "#239120" },
  "React Native": { icon: FaReact, color: "#61DAFB" },
  Expo: { icon: SiExpo, color: "#000000" },
  "Google Books API": { icon: SiGoogle, color: "#4285F4" },
  RxJs: { icon: SiReactivex, color: "#B7178C" },
  Flutter: { icon: SiFlutter, color: "#02569B" },
  Dart: { icon: SiDart, color: "#0175C2" },
  Datadog: { icon: SiDatadog, color: "#632CA6" },
  Mixpanel: { icon: SiMixpanel, color: "#7856FF" },
  Storybook: { icon: SiStorybook, color: "#FF4785" },
  "Redux.js": { icon: SiRedux, color: "#764ABC" },
  "Apollo Engine": { icon: SiGraphql, color: "#112B49" },
  "React Query": { icon: SiReact, color: "#FF4154" },
  "Claude Code": { icon: SiClaude, color: "#CC9966" },
  "Cursor AI": { icon: SiAnthropic, color: "#000000" },
  "OpenAI Codex": { icon: SiOpenai, color: "#412991" },
} as const;
