import {
  Briefcase,
  Cloud,
  Code,
  Code2,
  Github,
  Layers,
  Linkedin,
  Mail,
  MapPin,
  Server,
  User,
  Wrench,
} from "lucide-react";
import * as React from "react";
import { BsFileEarmarkSpreadsheet } from "react-icons/bs";
import { DiMsqlServer } from "react-icons/di";
import {
  FaAws,
  FaCss3,
  FaHtml5,
  FaNodeJs,
  FaPython,
  FaReact,
  FaSass,
} from "react-icons/fa";
import { GiBearFace } from "react-icons/gi";
import {
  SiAmazonwebservices,
  SiAngular,
  SiBootstrap,
  SiConfluence,
  SiCss3,
  SiD3Dotjs,
  SiDocker,
  SiExpo,
  SiExpress,
  SiFigma,
  SiFirebase,
  SiFlask,
  SiGit,
  SiGithub,
  SiGitlab,
  SiGoogle,
  SiGoogleads,
  SiGooglecloud,
  SiGraphql,
  SiHtml5,
  SiJasmine,
  SiJavascript,
  SiJenkins,
  SiJest,
  SiJira,
  SiJquery,
  SiLinux,
  SiLooker,
  SiMongodb,
  SiMui,
  SiMysql,
  SiNextdotjs,
  SiNginx,
  SiNodedotjs,
  SiNpm,
  SiPandas,
  SiPostgresql,
  SiPostman,
  SiPython,
  SiReact,
  SiReactivex,
  SiRedis,
  SiRedux,
  SiScikitlearn,
  SiStripe,
  SiStyledcomponents,
  SiTailwindcss,
  SiTelegram,
  SiTestinglibrary,
  SiTypescript,
  SiUnity,
  SiVercel,
  SiVite,
  SiWebpack,
  SiYarn,
  SiZoho,
} from "react-icons/si";
import { TbBrandCSharp } from "react-icons/tb";
import { VscCode } from "react-icons/vsc";

import {
  ContactInfo,
  ProficiencyLevel,
  TechnologyCategory,
  WorkExperienceEntry,
} from "@/lib/types";

export const NAV_ITEMS = [
  { href: "#about", label: "About Me", icon: User },
  { href: "#work-experience", label: "Experience", icon: Briefcase },
  { href: "#projects", label: "Projects", icon: Code2 },
  { href: "#tech-stack", label: "Tech Stack", icon: Layers },
  { href: "#contact", label: "Contact", icon: Mail },
];

export const EXPERIENCES: WorkExperienceEntry[] = [
  {
    company: "EPAM Systems",
    client: "Dow Jones",
    clientLink: "https://www.dowjones.com",
    companyLink: "https://www.epam.com",
    modality: "Remote",
    position: "Senior Software Engineer",
    startDate: "May 2022",
    endDate: "Present",
    responsibilities: [
      "Architected & delivered a modular, API-first integration layer for Dow Jones ad configurations, leveraging Node.js, Express.js and GraphQL. Designed REST and GraphQL endpoints to pull CMS metadata and map it to GAM ad‐unit hierarchies ensuring 99.8% data-mapping accuracy between legacy CMS structures and Google Ad Manager.",
      "Built a dynamic configuration management engine with a Next.js/React admin UI and a Node.js backend, using MongoDB for persisting templates and Redis for caching active configurations. Introduced template inheritance (allowing bulk updates via parent templates) and versioned change control (audit history, approvals, roll-back), which enabled 100% traceability of all ad-config changes, accelerated deployment velocity by 45%, and automatically detected & flagged 85% of configuration anomalies before reaching production.",
      "Collaborated cross-functionally with AdOps, RevOps, and Product teams to refine requirements, roadmap new features (e.g. ACE widget integration for in-page editing), and conduct performance tuning—profiling slow GraphQL resolvers with Apollo Engine and optimizing hot paths to reduce 95th-percentile API latency from 350 ms to 120 ms.",
    ],
    technologies: [
      "JavaScript",
      "HTML",
      "CSS",
      "TypeScript",
      "React",
      "Styled Components",
      "Next.js",
      "Node.js",
      "Express.js",
      "GraphQL",
      "MongoDB",
      "Redis",
      "AWS",
      "Jenkins",
      "Jest",
      "React Testing Library",
      "NPM",
      "Yarn",
      "NVM",
      "Postman",
      "Jira",
      "Confluence",
      "Google Ads",
    ],
  },
  {
    company: "Newtech S.R.L.",
    client: "Verizon",
    companyLink: "https://www.newtechsa.com/es/inicio",
    clientLink: "https://www.verizon.com",
    modality: "Remote",
    position: "Software Developer",
    startDate: "Aug 2021",
    endDate: "May 2022",
    responsibilities: [
      "Revamped Verizon's fault-reporting single-page application using Angular 11+, enabling Ahead-Of-Time (AOT) compilation, OnPush change detection, and lazy-loaded feature modules. These optimizations shrank the initial bundle by 25% and improved end-to-end load times by 18%.",
      "Eliminated over 2,000 lines of redundant TypeScript across shared services and components by enforcing the DRY principle, which reduced technical debt and cut regression defects by 30%.",
      "Built a comprehensive test suite with Jasmine, Karma and Protractor, achieving 85% code coverage. Employed HttpTestingController to mock backend responses and validate critical user flows without live services.",
      "Operated within an Agile/SCRUM environment using Jira for backlog management and Confluence for documentation. Collaborated closely with product owners and QA to define acceptance criteria, refine user stories and coordinate deployments through Jenkins pipelines.",
    ],
    technologies: [
      "JavaScript",
      "HTML",
      "CSS",
      "TypeScript",
      "Angular",
      "Angular CLI",
      "RxJS",
      "Node.js",
      "Jasmine",
      "Karma",
      "Postman",
      "GitLab",
      "Jenkins",
      "Jira",
      "Confluence",
    ],
  },
  {
    company: "IntelliSys D. Corp.",
    client: "Escuela Nacional de la Judicatura",
    companyLink: "https://intellisysdcorp.com/",
    clientLink: "https://juriteca.edu.do/base/domenj",
    modality: "On Site",
    position: "Software Engineer",
    startDate: "Nov 2020",
    endDate: "Aug 2021",
    responsibilities: [
      "Mentored & upskilled four junior front-end engineers, conducting weekly one-on-one coaching sessions, pair-programming workshops and structured code reviews. Introduced best practices in JavaScript (ES6+), React, Git and unit testing (Jest, React Testing Library), boosting the team's average story-completion rate by 25%.",
      "Architected and delivered a virtual library of Dominican jurisprudence for academic and legal professionals, collaborating with subject-matter experts to model case metadata and hierarchy. Built a React/Next.js front-end with full-text search and faceted filters, backed by a Node.js/Express API and PostgreSQL datastore. Optimized indexing and query performance—reducing search latency by 40%—and enhanced the legal consultation experience by 13%, as measured in user-satisfaction surveys.",
      "Collaborated cross-functionally with UX designers, legal researchers and QA analysts—gathering requirements, refining user stories in Jira, and authoring technical and user documentation in Confluence to streamline onboarding and maintenance.",
    ],
    technologies: [
      "JavaScript",
      "HTML",
      "CSS",
      "Sass",
      "React",
      "Bootstrap",
      "Node.js",
      "Express.js",
      "PostgreSQL",
      "NPM",
      "Jira",
    ],
  },
  {
    company: "IntelliSys D. Corp.",
    companyLink: "https://intellisysdcorp.com/",
    client: "Consejo Nacional de Competitividad (CNC)",
    clientLink: "https://cnc.gob.do",
    modality: "On Site",
    position: "Software Developer",
    startDate: "Jun 2020",
    endDate: "Nov 2020",
    responsibilities: [
      "Designed and implemented interactive dashboards with D3.js, creating line charts, bar charts, and map graphs that let users explore historical trends, apply category filters, and hover for exact values.",
      "Built a fully responsive UI with HTML5 and CSS3 (Flexbox, Media Queries), ensuring cross-browser compatibility and seamless layouts on desktop, tablet, and mobile. Established a modular design system for reusable chart components and info panels.",
      "Collaborated closely with storytellers and UX designers, running A/B tests and iterating on prototypes based on in-app feedback and usage metrics—resulting in a 31% lift in user satisfaction as measured by post-interact surveys.",
    ],
    technologies: ["JavaScript", "D3.js", "jQuery", "HTML", "CSS", "Jira"],
  },
  {
    company: "IntelliSys D. Corp.",
    client: "IntelliSys D. Corp.",
    companyLink: "https://intellisysdcorp.com/",
    clientLink: "https://intellisysdcorp.com/",
    modality: "On Site",
    position: "Software Engineer",
    startDate: "Apr 2019",
    endDate: "Jun 2020",
    responsibilities: [
      "Streamlined internal data collection pipeline by architecting and deploying Node.js microservices on Google Cloud Platform (Cloud Functions, and Cloud SQL). Each service ingested, validated and normalized employee and project metrics from multiple sources (CSV uploads, Google Spreadsheets, APIs), then wrote consolidated records into PostgreSQL for analytics.",
      "Built an administrative web application using React, Redux, Node.js/Express, HTML5 and Material UI, and Axios for REST API integration. Designed dynamic data grids, search/filter controls and editable forms for employee records, incorporating client-side validation and optimistic UI updates.",
    ],
    technologies: [
      "JavaScript",
      "HTML",
      "CSS",
      "React",
      "Material-UI",
      "Python",
      "Node.js",
      "Express.js",
      "Flask",
      "PostgreSQL",
      "GCP",
      "Jest",
      "NPM",
      "Looker",
      "Google Spreadsheets",
      "Jira",
      "Zoho",
    ],
  },
];

export const TECH_ICONS: Record<
  string,
  { icon: React.ComponentType<{ className?: string }>; color: string }
> = {
  React: { icon: FaReact, color: "#61DAFB" },
  "Next.js": { icon: FaReact, color: "#000000" },
  "Node.js": { icon: FaNodeJs, color: "#339933" },
  "Express.js": { icon: SiExpress, color: "#000000" },
  HTML: { icon: FaHtml5, color: "#E34F26" },
  GraphQL: { icon: SiGraphql, color: "#E10098" },
  AWS: { icon: FaAws, color: "#FF9900" },
  MongoDB: { icon: SiMongodb, color: "#47A248" },
  Redis: { icon: SiRedis, color: "#DC382D" },
  Jest: { icon: SiJest, color: "#C21325" },
  Jira: { icon: SiJira, color: "#0052CC" },
  "Google Ads": { icon: SiGoogleads, color: "#4285F4" },
  TypeScript: { icon: SiTypescript, color: "#3178C6" },
  JavaScript: { icon: SiJavascript, color: "#F7DF1E" },
  Angular: { icon: SiAngular, color: "#DD0031" },
  "Angular CLI": { icon: SiAngular, color: "#DD0031" },
  RxJS: { icon: SiReactivex, color: "#B7178C" },
  CSS: { icon: FaCss3, color: "#1572B6" },
  GitLab: { icon: SiGitlab, color: "#FC6D26" },
  Jenkins: { icon: SiJenkins, color: "#D33833" },
  Sass: { icon: FaSass, color: "#CC6699" },
  SQL: { icon: SiPostgresql, color: "#336791" },
  "D3.js": { icon: SiD3Dotjs, color: "#F9A03C" },
  jQuery: { icon: SiJquery, color: "#0769AD" },
  Python: { icon: FaPython, color: "#3776AB" },
  Flask: { icon: SiFlask, color: "#000000" },
  GCP: { icon: SiGooglecloud, color: "#4285F4" },
  PostgreSQL: { icon: SiPostgresql, color: "#336791" },
  Looker: { icon: SiLooker, color: "#4285F4" },
  "Material-UI": { icon: SiMui, color: "#007FFF" },
  Jasmine: { icon: SiJasmine, color: "#8A4182" },
  Postman: { icon: SiPostman, color: "#FF6C37" },
  Bootstrap: { icon: SiBootstrap, color: "#7952B3" },
  Zoho: { icon: SiZoho, color: "#0072c6" },
  "Google Spreadsheets": { icon: BsFileEarmarkSpreadsheet, color: "#34a853" },
  NPM: { icon: SiNpm, color: "#cb3837" },
  Karma: { icon: SiJasmine, color: "#8a4182" },
  Confluence: { icon: SiConfluence, color: "#0052cc" },
  NVM: { icon: SiNodedotjs, color: "#339933" },
  Yarn: { icon: SiYarn, color: "#2c8ebb" },
  "React Testing Library": { icon: SiTestinglibrary, color: "#e33332" },
  "Styled Components": { icon: SiStyledcomponents, color: "#D26AC2" },
  MySQL: { icon: SiMysql, color: "#4479A1" },
  Docker: { icon: SiDocker, color: "#2496ED" },
  "Material UI": { icon: SiMui, color: "#007FFF" },
  Zustand: { icon: GiBearFace, color: "#3E383E" },
  Stripe: { icon: SiStripe, color: "#6772E5" },
  Firebase: { icon: SiFirebase, color: "#FFCA28" },
  Figma: { icon: SiFigma, color: "#F24E1E" },
  "SQL Server": { icon: DiMsqlServer, color: "#CC2927" },
  "Telegram API": { icon: SiTelegram, color: "#0088cc" },
  Pandas: { icon: SiPandas, color: "#150458" },
  Sklearn: { icon: SiScikitlearn, color: "#F7931E" },
  Emotion: { icon: SiStyledcomponents, color: "#DB7093" },
  "Testing Library": { icon: SiTestinglibrary, color: "#E33332" },
  Express: { icon: SiExpress, color: "#000000" },
  Unity: { icon: SiUnity, color: "#000000" },
  "C#": { icon: TbBrandCSharp, color: "#239120" },
  "React Native": { icon: FaReact, color: "#61DAFB" },
  Expo: { icon: SiExpo, color: "#000000" },
  "Google Books API": { icon: SiGoogle, color: "#4285F4" },
  RxJs: { icon: SiReactivex, color: "#B7178C" },
} as const;

export const PROFICIENCY_CONFIG: Record<
  ProficiencyLevel,
  {
    label: string;
    color: string;
    bgColor: string;
    dotColor: string;
  }
> = {
  beginner: {
    label: "Beginner",
    color: "text-blue-600 dark:text-blue-400",
    bgColor:
      "bg-blue-50 dark:bg-blue-950/50 border-blue-200 dark:border-blue-800",
    dotColor: "bg-blue-400 dark:bg-blue-500",
  },
  intermediate: {
    label: "Intermediate",
    color: "text-yellow-600 dark:text-yellow-400",
    bgColor:
      "bg-yellow-50 dark:bg-yellow-950/50 border-yellow-200 dark:border-yellow-800",
    dotColor: "bg-yellow-400 dark:bg-yellow-500",
  },
  advanced: {
    label: "Advanced",
    color: "text-green-600 dark:text-green-400",
    bgColor:
      "bg-green-50 dark:bg-green-950/50 border-green-200 dark:border-green-800",
    dotColor: "bg-green-400 dark:bg-green-500",
  },
  expert: {
    label: "Expert",
    color: "text-purple-600 dark:text-purple-400",
    bgColor:
      "bg-purple-50 dark:bg-purple-950/50 border-purple-200 dark:border-purple-800",
    dotColor: "bg-purple-400 dark:bg-purple-500",
  },
};

export const TECHNOLOGIES: TechnologyCategory[] = [
  {
    category: "Frontend Development",
    categoryIcon: Code,
    description: "Building responsive, interactive user interfaces",
    skills: [
      {
        name: "React",
        icon: SiReact,
        proficiency: "expert",
        yearsOfExperience: 5,
        isCore: true,
        color: "#61DAFB",
      },
      {
        name: "Next.js",
        icon: SiNextdotjs,
        proficiency: "advanced",
        yearsOfExperience: 3,
        isCore: true,
        color: "#000000",
      },
      {
        name: "TypeScript",
        icon: SiTypescript,
        proficiency: "advanced",
        yearsOfExperience: 4,
        isCore: true,
        color: "#3178C6",
      },
      {
        name: "JavaScript (ES6+)",
        icon: SiJavascript,
        proficiency: "expert",
        yearsOfExperience: 6,
        isCore: true,
        color: "#F7DF1E",
      },
      {
        name: "HTML5",
        icon: SiHtml5,
        proficiency: "expert",
        yearsOfExperience: 6,
        color: "#E34F26",
      },
      {
        name: "CSS3 / Sass",
        icon: SiCss3,
        proficiency: "advanced",
        yearsOfExperience: 5,
        color: "#1572B6",
      },
      {
        name: "Tailwind CSS",
        icon: SiTailwindcss,
        proficiency: "advanced",
        yearsOfExperience: 2,
        color: "#06B6D4",
      },
      {
        name: "Angular 11+",
        icon: SiAngular,
        proficiency: "advanced",
        yearsOfExperience: 3,
        color: "#DD0031",
      },
      {
        name: "RxJS",
        icon: SiReactivex,
        proficiency: "intermediate",
        yearsOfExperience: 2,
        color: "#B7178C",
      },
      {
        name: "Redux",
        icon: SiRedux,
        proficiency: "advanced",
        yearsOfExperience: 3,
        color: "#764ABC",
      },
      {
        name: "D3.js",
        icon: SiD3Dotjs,
        proficiency: "intermediate",
        yearsOfExperience: 2,
        color: "#F9A03C",
      },
      {
        name: "jQuery",
        icon: SiJquery,
        proficiency: "advanced",
        yearsOfExperience: 4,
        color: "#0769AD",
      },
    ],
  },
  {
    category: "Backend Development",
    categoryIcon: Server,
    description: "Server-side logic, APIs, and database management",
    skills: [
      {
        name: "Node.js",
        icon: SiNodedotjs,
        proficiency: "expert",
        yearsOfExperience: 5,
        isCore: true,
        color: "#339933",
      },
      {
        name: "Express.js",
        icon: SiExpress,
        proficiency: "advanced",
        yearsOfExperience: 4,
        isCore: true,
        color: "#000000",
      },
      {
        name: "GraphQL",
        icon: SiGraphql,
        proficiency: "advanced",
        yearsOfExperience: 3,
        color: "#E10098",
      },
      {
        name: "REST APIs",
        icon: SiGraphql,
        proficiency: "expert",
        yearsOfExperience: 5,
        color: "#E10098",
      },
      {
        name: "PostgreSQL",
        icon: SiPostgresql,
        proficiency: "advanced",
        yearsOfExperience: 4,
        color: "#336791",
      },
      {
        name: "MongoDB",
        icon: SiMongodb,
        proficiency: "advanced",
        yearsOfExperience: 3,
        color: "#47A248",
      },
      {
        name: "Redis",
        icon: SiRedis,
        proficiency: "intermediate",
        yearsOfExperience: 3,
        color: "#DC382D",
      },
      {
        name: "SQL",
        icon: SiMysql,
        proficiency: "advanced",
        yearsOfExperience: 4,
        color: "#4479A1",
      },
      {
        name: "Python / Flask",
        icon: SiPython,
        proficiency: "intermediate",
        yearsOfExperience: 2,
        color: "#3776AB",
      },
    ],
  },
  {
    category: "DevOps & Cloud",
    categoryIcon: Cloud,
    description: "Deployment, infrastructure, and cloud services",
    skills: [
      {
        name: "Docker",
        icon: SiDocker,
        proficiency: "intermediate",
        yearsOfExperience: 2,
        color: "#2496ED",
      },
      {
        name: "AWS",
        icon: SiAmazonwebservices,
        proficiency: "advanced",
        yearsOfExperience: 3,
        isCore: true,
        color: "#FF9900",
      },
      {
        name: "Google Cloud",
        icon: SiGooglecloud,
        proficiency: "intermediate",
        yearsOfExperience: 2,
        color: "#4285F4",
      },
      {
        name: "CI/CD",
        icon: SiGithub,
        proficiency: "advanced",
        yearsOfExperience: 3,
        color: "#181717",
      },
      {
        name: "Git",
        icon: SiGit,
        proficiency: "expert",
        yearsOfExperience: 6,
        color: "#F05032",
      },
      {
        name: "Linux",
        icon: SiLinux,
        proficiency: "intermediate",
        yearsOfExperience: 3,
        color: "#FCC624",
      },
      {
        name: "Nginx",
        icon: SiNginx,
        proficiency: "intermediate",
        yearsOfExperience: 2,
        color: "#009639",
      },
    ],
  },
  {
    category: "Development Tools",
    categoryIcon: Wrench,
    description: "Development environment and productivity tools",
    skills: [
      {
        name: "VS Code",
        icon: VscCode,
        proficiency: "expert",
        yearsOfExperience: 5,
        color: "#007ACC",
      },
      {
        name: "Webpack",
        icon: SiWebpack,
        proficiency: "intermediate",
        yearsOfExperience: 3,
        color: "#8DD6F9",
      },
      {
        name: "Vite",
        icon: SiVite,
        proficiency: "advanced",
        yearsOfExperience: 2,
        color: "#646CFF",
      },
      {
        name: "Jest",
        icon: SiJest,
        proficiency: "advanced",
        yearsOfExperience: 3,
        color: "#C21325",
      },
      {
        name: "GitHub",
        icon: SiGithub,
        proficiency: "expert",
        yearsOfExperience: 6,
        color: "#181717",
      },
      {
        name: "Postman",
        icon: SiPostman,
        proficiency: "advanced",
        yearsOfExperience: 4,
        color: "#FF6C37",
      },
      {
        name: "Figma",
        icon: SiFigma,
        proficiency: "intermediate",
        yearsOfExperience: 2,
        color: "#F24E1E",
      },
      {
        name: "Vercel",
        icon: SiVercel,
        proficiency: "advanced",
        yearsOfExperience: 2,
        color: "#000000",
      },
    ],
  },
];

export const PROJECTS = [
  {
    id: "caribbean-cinemas",
    title: "Cine Caribbean Cinemas",
    description:
      "🎞️ A modern web platform that revolutionizes the Caribbean cinema experience. 🍿",
    image: "/projects/caribbean-cinemas.png",
    link: "http://licemcinema.tech",
    repo: "https://github.com/jrodriguezdiazz/cinema-licem",
    technologies: [
      "React",
      "Node.js",
      "MySQL",
      "Docker",
      "Material UI",
      "Zustand",
      "AWS",
      "Stripe",
      "Firebase",
      "Figma",
    ],
    status: "offline",
    featured: true,
  },
  {
    id: "belphoebe",
    title: "Belphoebe",
    description:
      "🤖 Belphoebe is the virtual assistant of LICEM-Retro, her goal is to help you rent films on our platform, where you will find a great diversity of films 💁🏻‍♀️",
    image: "/projects/belphoebe.png",
    link: "https://t.me/BelphoebeBot",
    repo: "https://github.com/jrodriguezdiazz/Belphoebe",
    technologies: ["Python", "SQL Server", "Telegram API", "Pandas", "Sklearn"],
    status: "offline",
    featured: true,
  },
  {
    id: "explorando-ando",
    title: "Explorando Ando",
    description:
      "🌴 Explorando Ando is the web platform for travel lovers in the Dominican Republic. 🇩🇴",
    image: "/projects/explorando-ando.png",
    link: "https://github.com/jrodriguezdiazz/explorando-ando",
    repo: "https://github.com/jrodriguezdiazz/explorando-ando",
    technologies: [
      "React",
      "Emotion",
      "Bootstrap",
      "Testing Library",
      "Express",
      "PostgreSQL",
      "Zustand",
    ],
    status: "offline",
    featured: true,
  },
  {
    id: "flixo",
    title: "Flixo",
    description:
      "🤳🏾 Made to share your best moments and smiles with your friends. 🛜",
    image: "/projects/flixo.png",
    link: "https://github.com/jrodriguezdiazz/Flixo",
    repo: "https://github.com/jrodriguezdiazz/Flixo",
    technologies: ["React Native", "Firebase", "Expo", "Yarn", "Zustand"],
    status: "offline",
    featured: true,
  },
  {
    id: "school-administrator",
    title: "School Administrator",
    description:
      "🏫This platform is an example of a system that will allow managing students of a school. 📅",
    image: "/projects/school-administrator.png",
    link: "https://school-administrator-320621.web.app/",
    repo: "https://github.com/jrodriguezdiazz/school-administrator",
    technologies: [
      "Node.js",
      "Firebase",
      "SQL Server",
      "Angular",
      "Angular CLI",
      "TypeScript",
      "RxJs",
    ],
    status: "live",
    featured: false,
  },
  {
    id: "book-search-engine",
    title: "Book Search Engine",
    description:
      "🔍 An application that will allow users to search for books by entering a query (Title, Author, etc). Display the resulting books in a list on the page with all the corresponding data. 📚",
    image: "/projects/book-search-engine.png",
    link: "https://book-search-engine-black.vercel.app",
    repo: "https://github.com/jrodriguezdiazz/book-search-engine",
    technologies: ["React", "Material-UI", "TypeScript", "Google Books API"],
    status: "live",
    featured: false,
  },
  {
    id: "Dragon-s-Quest",
    title: "Dragon's-Quest",
    description:
      "🎮 Dragon's Quest is an exciting 2D platformer game that takes players on a thrilling adventure. Embark on a quest through vibrant pixelated worlds. 🐲",
    image: "/projects/dragon-quest.png",
    link: "https://jrodriguezdiazz.itch.io/dragons-quest",
    repo: "https://github.com/jrodriguezdiazz/Dragon-s-Quest",
    technologies: ["Unity", "C#"],
    status: "live",
    featured: true,
  },
];

export const STATUS_CONFIG = {
  live: {
    color: "bg-green-500",
    text: "Live",
    textColor: "text-green-700",
    bgColor: "bg-green-50",
  },
  offline: {
    color: "bg-gray-500",
    text: "Offline",
    textColor: "text-gray-700",
    bgColor: "bg-gray-50",
  },
};

export const CONTACT_INFO: ContactInfo[] = [
  {
    icon: Mail,
    label: "Email",
    value: "jrodriguezdiazz@outlook.com",
    href: "mailto:jrodriguezdiazz@outlook.com",
  },
  {
    icon: Linkedin,
    label: "LinkedIn",
    value: "linkedin.com/in/jrodriguezdiazz",
    href: "https://linkedin.com/in/jrodriguezdiazz",
  },
  {
    icon: Github,
    label: "GitHub",
    value: "github.com/jrodriguezdiazz",
    href: "https://github.com/jrodriguezdiazz",
  },
  {
    icon: MapPin,
    label: "Location",
    value: "Espaillat, Dominican Republic",
  },
];

export const RESPONSE_TYPE = "Usually responds within 24 hours";
